---
# Create the elastic namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    chart: {{ include "efk-aks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}